### ISSUE TITLE
airflow in docker compose initdb 1 failing 

### ISSUE THREAD

**Issue by tcg-peter** [xnuinside/airflow_in_docker_compose#10]
Everything else was running great but this container is failing 
![image](https://user-images.githubusercontent.com/73512075/104264389-1d7a3600-54be-11eb-90e3-28c1182e4372.png)

**Comment by xnuinside** [comment]
Hi @tcg-peter ! This log for 1st run or next runs? Also other services runs & works correct? Looks like just command fail because admin user already in dB.

**Comment by tcg-peter** [comment]
i did run it a couple time before i can get `localhost:8080` running, but i delete all the docker container `docker stop $(docker ps -aq)` and image `docker rm $(docker ps -a -q)` before i got this error, so it could be in the 1st run

Everything else run correctly
![image](https://user-images.githubusercontent.com/73512075/104271051-751f9e00-54cc-11eb-8eb5-8dc588c710f6.png)

However i can't see any dag in `localhost:8080`
![image](https://user-images.githubusercontent.com/73512075/104271099-91233f80-54cc-11eb-88de-94cf30643e1d.png)

**Comment by xnuinside** [comment]
@tcg-peter did you delete DB volume? Because all data from dB stored on volume and it is not inside container.

**Comment by xnuinside** [comment]
Also, Can you send me logs from scheduler container and webserver?

**Comment by tcg-peter** [comment]
@xnuinside
i do have data in volume, but i don't think i should delete it, is there a way to work around ?
Here is the scheduler 
![image](https://user-images.githubusercontent.com/73512075/104283052-896e9580-54e2-11eb-9a87-f2ddd2f01f73.png)
webserver 
![image](https://user-images.githubusercontent.com/73512075/104283085-97bcb180-54e2-11eb-959e-0c955fda8432.png)

**Comment by tcg-peter** [comment]
@xnuinside i deleted the volume and `airflow in docker compose initdb 1` failed after i login as admin

**Comment by xnuinside** [comment]
@tcg-peter if you don't want to keep history and data in DB after container deletion - you can just remove volume from docker-compose file from postgres service - https://github.com/xnuinside/airflow_in_docker_compose/blob/master/docker-compose-2.0-with-celery-executor.yml#L17

**Comment by tcg-peter** [comment]
@xnuinside yes but it's still fail after i after i delete the volume

**Comment by tcg-peter** [comment]
I'm running on WSL, and i changed `/opt/` to `/usr/local/` according to this issue #4
