### ISSUE TITLE
Bad FERNET key

### ISSUE THREAD

**Issue by igormusinov** [xnuinside/airflow_in_docker_compose#12]
I faced the problem with FERNET key from https://github.com/xnuinside/airflow_in_docker_compose/blob/master/.env

`airflow.exceptions.AirflowException: Could not create Fernet object: Invalid base64-encoded string: number of data characters (53) cannot be 1 more than a multiple of 4`

Generating by this instruction helped
https://airflow.apache.org/docs/apache-airflow/stable/security/secrets/fernet.html

**Comment by xnuinside** [comment]
I'm not sure why I cannot get this error log, but anyway - I changed the fernet key - https://github.com/xnuinside/airflow_in_docker_compose/pull/14. Thank you for reporting the issue! I merged the fix, so I will close an issue. Thanks one more time!
