### ISSUE TITLE
docker image from official

### ISSUE THREAD

**Issue by Syrymbatyr** [xnuinside/airflow_in_docker_compose#3]
Привет! 
Апач выложил офф версию в dockerhub.
Вы не меняли еще compose файл?

**Comment by xnuinside** [comment]
@Syrymbatyr, привет! Этот докер хаб был давно. Обратите внимание на докер файл этих имиджей https://hub.docker.com/r/apache/airflow/dockerfile и комментарии в нем, а именно  
WARNING: THIS DOCKERFILE IS NOT INTENDED FOR PRODUCTION USE OR DEPLOYMENT. Пока не закрыт пропозал по официальному образу готовому для продакшена https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-26+Production-ready+Airflow+Docker+Image+and+helm+chart и соответствующий комментарий указанный выше не исчезнет из имиджа - будет использоваться имидж puckle.
