### ISSUE TITLE
Latest docker compose not working at the startp up

### ISSUE THREAD

**Issue by oriolcmp** [xnuinside/airflow_in_docker_compose#5]
Hi, 

I just cloned your repo I did:  **docker-compose -f docker-compose-with-celery-executor.yml up**
But I get these messages:

worker_1     | DB_BACKEND=postgresql+psycopg2
worker_1     | DB_HOST=postgres
worker_1     | DB_PORT=5432
redis_1      | 1:M 13 Aug 2020 14:08:08.174 * DB loaded from disk: 0.000 seconds
redis_1      | 1:M 13 Aug 2020 14:08:08.174 * Ready to accept connections
initdb_1     | DB: postgresql+psycopg2://airflow:***@postgres:5432/airflow
initdb_1     | [2020-08-13 14:08:10,833] {db.py:378} INFO - Creating tables
initdb_1     | Traceback (most recent call last):
initdb_1     |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
initdb_1     |     return fn()
initdb_1     |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
initdb_1     |     return _ConnectionFairy._checkout(self)
initdb_1     |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
initdb_1     |     fairy = _ConnectionRecord.checkout(pool)
initdb_1     |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
initdb_1     |     rec = pool._do_get()
initdb_1     |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
initdb_1     |     self._dec_overflow()
initdb_1     |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
initdb_1     |     exc_value, with_traceback=exc_tb,
initdb_1     |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
initdb_1     |     raise exception
initdb_1     |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
initdb_1     |     return self._create_connection()
initdb_1     |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
initdb_1     |     return _ConnectionRecord(self)
initdb_1     |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
initdb_1     |     self.__connect(first_connect_check=True)
initdb_1     |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
initdb_1     |     pool.logger.debug("Error on connect(): %s", e)
initdb_1     |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
initdb_1     |     exc_value, with_traceback=exc_tb,
initdb_1     |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
initdb_1     |     raise exception
initdb_1     |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
initdb_1     |     connection = pool._invoke_creator(self)
initdb_1     |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
initdb_1     |     return dialect.connect(*cargs, **cparams)
initdb_1     |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 493, in connect
initdb_1     |     return self.dbapi.connect(*cargs, **cparams)
initdb_1     |   File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
initdb_1     |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
initdb_1     | psycopg2.OperationalError: could not connect to server: Connection refused
initdb_1     | 	Is the server running on host "postgres" (172.25.0.3) and accepting
initdb_1     | 	TCP/IP connections on port 5432?
initdb_1     |
initdb_1     |

**Comment by xnuinside** [comment]
start separate postgres contianer, wait till it will be up and when start other containers

initdb_1 | psycopg2.OperationalError: could not connect to server: Connection refused
initdb_1 | Is the server running on host "postgres" (172.25.0.3) and accepting 

this issue because postgres did not create DB & up yet, it possible depend on local machine

**Comment by oriolcmp** [comment]
Ok, if I start each container separately airflow starts. It is kind of weird to do it like that considering that docker compose is made to avoid this.
Anyways, after starting and loading a dag, I trigger the dag and the dag is in running state but it the never starts any of the tasks.
How is that possible? Am I missing anything?
Thanks

**Comment by xnuinside** [comment]
@oriolcmp no need to start each container separately, problem only in postgres for first run, you can kill docker-compose and up all containers together - you will see that all ook

**Comment by xnuinside** [comment]
added restart policy to avoid this issue on clean up & run https://github.com/xnuinside/airflow_in_docker_compose/pull/6/files
